name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
- name: Download a Build Artifact
  uses: actions/download-artifact@v2.1.0
  with:
    # Artifact name
    name: # optional
    # Destination path
    path: # optional
- name: SonarQube Scanner
  uses: ItsEcholot/sonarqube-action@v0.0.2
